alignment_filter:
  ALEN_RATIO_LOW: 0.93
  ALEN_RATIO_HIGH: 1.07
  ID_LONG: 0.8
  ID_SHORT: 0.9
  SCOV_LONG: 0.99
  SCOV_SHORT: 0.99
  SHORT_LEN: 4000


collapse_reads:
  QCOV_TH: 0
  SCOV_TH: 0.99
  ID_TH: 0.8
  DELTA: 50
  FA_COV_TH: 0.99
  MA_TH: 0
  MA_DELTA: 1000
  SHORT_CENTER_LEN: 4000
  MIN_SHORT_CENTER_NUM: 5
  CENTER_MIN_SUPPORT: 3
  MIN_LA_RA: 5
  
  IQR_MIN_SUPPORT: 5
  IQR_TH1: 0.03
  IQR_TH2: 0.08
  LRA_MIN: 3
self_ligation:
  min_align_len: 400
  min_cov: 0.05
  max_cov: 0.9
  ratio_lower: 0.93
  ratio_upper: 1.07
  cov_sum: 0.95
  query_chain_lower: 0.9
  query_chain_upper: 1.11
  subject_chain_lower: 0.87
  subject_chain_upper: 1.15


rep_superbin:
  REP_STAT: "Initial_rep_stat.txt"
  OUT_SUPERREP: "Finalrep_summary.txt"
  
  ID_TH: 0.85
  SCOV_TH: 0.98
  ALEN_RATIO_LOW: 0.9
  ALEN_RATIO_HIGH: 1.1
  QCOV_MAX: 0.9
  SHORT_LEN: 3000
  ID_TH_SHORT: 0.9
  SCOV_TH_SHORT: 0.9
  QCOV_MAX_SHORT: 0.7

  QCOV_TH: 0.98
  SCOV_TH2: 0.98
  ID_TH2: 0.8
  LEN_RATIO_LOW: 0.9
  LEN_RATIO_HIGH: 1.1
  STRONG_ID_TH: 0.9
  STRONG_SCOV_TH: 0.99
  STRONG_QCOV_TH: 0.95
  
racon_polish:
  aln_ratio_low: 0.93
  aln_ratio_high: 1.07 
  min_len_long: 4000 
  min_identity_long: 0.75
  min_qcov_long: 0.98     
  min_identity_short: 0.9
  min_qcov_short: 0.98 

